// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrCenter.Persistence;

#nullable disable

namespace PrCenter.Persistence.Migrations
{
    [DbContext(typeof(PrCenterDbContext))]
    [Migration("20260712164659_AddTokenVaultAndSecurity")]
    partial class AddTokenVaultAndSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PrCenter.Persistence.AppSecurity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Iterations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KdfVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemoryKib")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parallelism")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SentinelCiphertext")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SentinelNonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SentinelTag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("AppSecurity");
                });

            modelBuilder.Entity("PrCenter.Persistence.LastSeenMarker", b =>
                {
                    b.Property<string>("PullRequestId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PullRequestId");

                    b.ToTable("LastSeenMarkers");
                });

            modelBuilder.Entity("PrCenter.Persistence.OwnerToken", b =>
                {
                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Owner");

                    b.ToTable("OwnerTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
