// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrCenter.Persistence;

#nullable disable

namespace PrCenter.Persistence.Migrations
{
    [DbContext(typeof(PrCenterDbContext))]
    partial class PrCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PrCenter.Persistence.LastSeenMarker", b =>
                {
                    b.Property<string>("PullRequestId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PullRequestId");

                    b.ToTable("LastSeenMarkers");
                });
#pragma warning restore 612, 618
        }
    }
}
