// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrCenter.Persistence;

#nullable disable

namespace PrCenter.Persistence.Migrations
{
    [DbContext(typeof(PrCenterDbContext))]
    partial class PrCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PrCenter.Persistence.AppSecurity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Iterations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KdfVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemoryKib")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parallelism")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SentinelCiphertext")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SentinelNonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SentinelTag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("AppSecurity");
                });

            modelBuilder.Entity("PrCenter.Persistence.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PollIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("PrCenter.Persistence.OwnerToken", b =>
                {
                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Owner");

                    b.ToTable("OwnerTokens");
                });

            modelBuilder.Entity("PrCenter.Persistence.PollOwnerDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApprovedExclusions")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarriedOverCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClosedOrMergedExclusions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DerivedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DraftExclusions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForeignItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("PollRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PullRequestIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RateLimitCost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RateLimitRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RateLimitResetAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedLogin")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReviewedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UntrackedExclusions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PollRunId");

                    b.ToTable("PollOwnerDiagnostics");
                });

            modelBuilder.Entity("PrCenter.Persistence.PollRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguredOwners")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PollId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublishedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PollId")
                        .IsUnique();

                    b.ToTable("PollRuns");
                });

            modelBuilder.Entity("PrCenter.Persistence.PollOwnerDiagnostic", b =>
                {
                    b.HasOne("PrCenter.Persistence.PollRun", "PollRun")
                        .WithMany("Owners")
                        .HasForeignKey("PollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PollRun");
                });

            modelBuilder.Entity("PrCenter.Persistence.PollRun", b =>
                {
                    b.Navigation("Owners");
                });
#pragma warning restore 612, 618
        }
    }
}
